services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"  # Este está bien
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/palettes.db
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    ports:
      - "8081:80"  # ⬅️ CAMBIAR de 8080 a 8081
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
    restart: unless-stopped